In [ ]:
from sklearn import preprocessing

In [1]:
import numpy as np

In [2]:
a = 'hello'

In [3]:
a

'hello'

In [4]:
X = np.array([[4,3658],[3,7231],[23,3723],[31,5176],[4,11485],[10,4143],[9,489],[5,5311],[31,5682],[9,3884],[7,9848],[6,3934],[3,7261],[9,3392],[3,7738],[185,89770],[29,3630],[10,4747],[25,4515],[35,5729],[2,2400],[3,4239],[4,304],[4,3600],[6,3651],[27,4917],[2,2545],[5,5277],[4,7691],[4,7591],[4,4949],[8,3959],[4,9433],[12,5961],[2,2176],[3,7637],[7,109],[4,5609],[16,5284],[3,3690],[6,3617],[4,3903],[8,7710],[29,5083],[7,3835],[4,7941],[3,5218],[25,15502],[23,4144],[7,3956],[8,4294],[4,3787],[16,4076],[4,5823],[34,4804],[5,10894],[8,3819],[4,8036],[2,2377],[4,80],[2,746],[3,8520],[46,8356],[3,7361],[4,7418],[2,4805],[6,4292],[40,13652],[66,11519],[4,6721],[22,3729],[12,15939],[4,8802],[3,7689],[33,5971],[8,3810],[13,2665],[146,14326],[6,14978],[25,4417],[5,9775],[8,4418],[9,4737],[3,7391],[2,5785],[5,14355],[181,47823],[3,5468],[6,8973],[7,9080],[6,6222],[3,5796],[60,10372],[6,6745],[8,4473],[51,9207],[21,3842],[23,4207],[25,4052],[7,16829],[42,15174],[6,3758],[13,199],[31,5468],[31,5409],[23,4081],[9,5685],[29,5014],[312,53350],[3,4731],[25,4096],[11,6068],[5,11220],[39,7027],[5,4501],[34,3698],[4,9399],[10,4630],[10,5349],[8,4225],[3,4675],[16,14617],[4,5095],[4,167],[3,5340],[20,3612],[7,6790],[20,16244],[9,7859],[3,7331],[32,5675],[6,8887],[6,3734],[18,8262],[50,8620],[4,7428],[4,135],[7,4429],[9,3616],[18,7649],[9,9440],[4,8354],[2,1999],[34,5967],[2,2510],[22,3890],[33,5960],[4,5110],[3,4232],[8,3981],[3,4500],[539,84777],[3,7632],[71,12488],[3,7805],[2,1800],[20,3664],[5,7624],[3,7672],[23,4113],[5,11765],[4,1054],[4,9847],[2,3050],[21,3663],[3,7249],[8,10572],[15,7190],[4,7868],[16,2803],[3,3743],[3,7494],[4,9927],[4,4377],[33,6197],[7,8069],[4,10455],[12,5516],[6,3893],[55,23350],[11,5609],[7,8052],[11,6893],[22,3882],[8,10248],[4,4175],[3,5150],[6,13674],[21,3168],[3,358],[13,6357],[2,5752],[3,9060],[10,3809],[28,4936],[12,3745],[8,3643],[2,101],[27,7464],[8,88],[36,6579],[12,5926],[4,7764],[7,6156],[9,10102],[40,7266],[8,3814],[8,3864],[17,6428],[5,3945],[4,4820],[23,3855],[6,3776],[2,2835],[4,3506],[9,4958],[15,6642],[36,6184],[3,7747],[8,4101],[24,4315],[14,8074],[29,12354],[4,8308],[21,3685],[22,4003],[5,4266],[33,5896],[5,6068],[8,4418],[12,5510],[8,6574],[22,3923],[8,3990],[8,3734],[4,5547],[8,4214],[24,4153],[17,7437],[8,4175],[20,8807],[9,6814],[6,12433],[5,3765],[37,6147],[12,5106],[4,3710],[7,17320],[10,3832],[10,3670],[20,3622],[4,8066],[6,14429],[13,846],[106,8502],[13,6727],[7,6636],[2,3173],[11,10959],[2,2466],[28,5101],[3,7410],[27,4482],[64,10898],[6,7026],[8,3818],[95,72671],[3,7478],[23,3919],[1,24],[6,4511],[8,4173],[27,4929],[27,4895],[4,8911],[4,13834],[4,4971],[8,658],[3,8561],[8,6964],[6,3954],[4,4319],[28,4918],[4,4601],[4,8843],[25,4508],[4,9510],[4,8349],[35,6196],[33,5859],[8,3855],[12,4875],[4,5364],[47,8449],[22,3940],[1,742],[2,2725],[32,5781],[71,12639],[4,8405],[4,3956],[3,125],[12,5626],[38,6697],[36,6477],[2,9018],[3,7466],[24,4359],[4,141],[8,4623],[31,5558],[2,4853],[10,13736],[11,15263],[14,6031],[4,9896],[13,199],[141,75683],[6,10217],[36,6088],[4,2477],[3,1923],[3,647],[3,7582],[4,5255],[25,4241],[4,4084],[24,4345],[4,5622],[8,3488],[4,2673],[7,4470],[5,216],[1301,283449],[10,7312],[7,109],[45,8102],[24,4196],[20,5245],[32,5749],[3,7216],[69,12528],[577,260502],[4,8225],[3,7388],[19,5145],[24,4129],[3,9170],[10,4765],[25,4569],[3,7636],[4,3599],[9,6465],[4,8603],[4,4717],[20,6195],[8,4064],[10,6199],[8,4432],[28,4858],[5,5521],[3,4018],[4,2783],[9,22124],[39,15785],[6,3682],[24,11841],[20,3652],[10,5173],[22,15543],[10,5594],[3,7549],[37,6307],[1301,283449],[29,5158],[3,9813],[20,9019],[8,88],[18,13958],[218,103574],[5,5593],[3,9161],[7,3633],[8,1170],[29,5220],[3,5659],[9,6657],[5,1774],[4,4849],[4,2187],[8,4048],[5,3846],[4,2055],[238,108836],[8,3858],[10,5068],[9,4212],[8,3728],[3,2314],[4,8494],[17,12487],[3,7540],[4,8206],[43,7553],[6,8149],[6,6153],[9,2460],[18,15971],[4,5060],[8,3651],[26,4601],[4,9206],[56,9642],[4,2659],[1,39],[8,4879],[2,2852],[21,3683],[28,4952],[12,6612],[96,49308],[10,5036],[1301,283449],[6,11920],[2,262],[2,314],[4,6499],[7,4869],[17,3709],[4,4437],[4,7834],[4,7707],[3,7419],[8,6387],[17,3692],[13,199],[27,4640],[4,7846],[4,9881],[7,15722],[20,4764],[32,21400],[9,4999],[27,4306],[3,97],[18,4297],[4,4749],[6,4480],[2,2918],[8,4265],[4,4122],[138,37717],[3,7653],[6,14797],[26,4564],[8,9341],[51,21055],[3,4953],[10,5166],[3,8159],[10,5778],[7,628],[8,12768],[33,5843],[26,4825],[23,2681],[6,11779],[6,3740],[9,4515],[27,4652],[4,8912],[4,7504],[23,4211],[24,11508],[5,3889],[4,5634],[5,5811],[3,4355],[11,6866],[28,4630],[4,7382],[4,8518],[52,25883],[2,2060],[25,4179],[12,4933],[2,3600],[148,54259],[3,6187],[14,3094],[8,3651],[13,2197],[6,3931],[27,4903],[4,4204],[6,9703],[5,5495],[82,14670],[11,10651],[3,7682],[6,4255],[5,5463],[3,7425],[8,88],[10,5233],[9,9019],[35,6277],[6,3889],[35,6101],[25,4474],[23,4177],[3,8677],[4,4579],[29,5257],[4,4372],[4,7318],[10,5551],[14,14248],[9,272],[5,5692],[762,117700],[4,5541],[13,11778],[25,10499],[61,28537],[4,8907],[10,5529],[8,9910],[17,8024],[28,12027],[19,10431],[4,1778],[41,7336],[10,4989],[7,3871],[6,8991],[1301,283449],[15,6187],[12,17031],[1,60],[3,7823],[14,6368],[7,3953],[4,8019],[30,5167],[27,4880],[3,7423],[6,9981],[2,6941],[4,4215],[10,4622],[4,5424],[1,41],[34,14289],[3,7900],[53,27254],[308,84245],[82,8514],[3,8917],[2,4105],[3,8559],[49,8022],[6,10800],[4,3688],[27,4075],[6,4636],[3,9348],[7,4573],[4,8100],[10,3765],[31,11301],[4,117],[22,3613],[8,4749],[35,6101],[10,4126],[118,90951],[4,8967],[6,8371],[22,10761],[28,4226],[24,4205],[4,8041],[5,11335],[4,5072],[7,132],[32,17714],[6,12932],[33,5672],[4,6460],[6,7605],[1301,283449],[10,4378],[4,6787],[29,5104],[8,5526],[3,8809],[2,323],[1301,283449],[4,6063],[5,14739],[25,4473],[8,4169],[29,5165],[4,2388],[28,4640],[10,4616],[8,4468],[2,1803],[25,4478],[38,6671],[8,3903],[8,4424],[2,1800],[22,4004],[31,5400],[4,10116],[6,16772],[4,11241],[8,4097],[10,4640],[10,5986],[22,14050],[3,7387],[5,13144],[4,4164],[25,4388],[3,860],[23,4260],[4,3761],[11,2282],[8,3971],[8,4432],[5,12217],[22,10538],[25,4264],[4,4148],[33,5779],[4,4475],[4,10967],[85,40295],[13,7603],[16,8319],[2,3325],[37,6580],[4,12735],[11,2660],[4,11222],[36,6596],[28,4952],[4,8171],[4,3475],[6,4609],[28,4889],[6,15622],[32,5514],[6,5574],[12,5965],[6,10112],[8,4537],[2,5705],[26,4413],[45,7899],[4,9541],[3,7231],[5,5037],[6,16350],[8,6408],[30,5210],[24,4177],[6,3655],[3,7214],[9,4324],[26,4536],[5,4716],[4,4137],[25,4515],[14,6097],[4,8262],[28,4651],[10,5339],[15,8177],[28,3404],[38,15588],[22,3891],[3,7886],[3,4400],[21,3812],[7,6548],[22,6558],[8,3686],[4,7893],[27,4228],[8,4135],[6,6196],[45,7903],[3,8492],[10,5408],[6,6938],[8,7159],[4,10104],[3,8019],[4,3907],[9,21402],[2,2000],[3,7310],[71,15506],[8,88],[9,8793],[4,7852],[16,6379],[5,5218],[4,9258],[189,29074],[6,4287],[8,6038],[20,3670],[4,4582],[33,5703],[8,3620],[18,3363],[10,16173],[5,7500],[5,13004],[5,11265],[15,6571],[4,11153],[8,3697],[34,5968],[4,4956],[11,5569],[40,6412],[250,36954],[4,7719],[8,1260],[16,3888],[6,246],[4,9126],[32,5749],[6,19977],[41,13467],[5,14686],[3,7343],[10,4905],[14,6356],[5,3997],[7,4085],[2,314],[178,25944],[36,6412],[26,4354],[14,17502],[4,8224],[4,2563],[29,5358],[22,3682],[4,4387],[16,7048],[6,5826],[6,3712],[6,6590],[3,3942],[10,4515],[4,14745],[3,7816],[4,8730],[7,3814],[123,92775],[8,4193],[6,3613],[2,3084],[2,2902],[712,160017],[12,5725],[26,4694],[34,6172],[8,6392],[21,3752],[23,3976],[3,9294],[6,7439],[8,16995],[90,48991],[21,3615],[7,6583],[32,5706],[4,5400],[5,10965],[7,4541],[28,5012],[7,4215],[25,3796],[35,6116],[11,8624],[3,5172],[37,6805],[23,3618],[45,7413],[24,3869],[8,4009],[11,6503],[14,2712],[23,4082],[8,4099],[6,4717],[15,11294],[21,3747],[20,7561],[4,6830],[4,33],[3,494],[34,6080],[9,4221],[21,3708],[33,5456],[28,5056],[6,5171],[69,10736],[30,5478],[54,6551],[28,12171],[3,130],[5,7119],[7,5356],[11,5144],[579,84904],[16,2681],[10,5198],[4,140],[24,4435],[3,7205],[9,5314],[1,1],[22,3753],[4,10881],[8,3301],[35,6187],[23,4286],[4,4854],[4,4135],[21,3692],[36,6277],[8,4144],[7,1712],[37,21005],[3,7346],[97,49215],[2,4530],[22,14690],[52,18282],[3,7337],[3,7239],[21,3720],[15,3837],[6,7962],[10,4750],[712,160017],[4,9804],[51,8954],[22,3958],[3,7260],[14,5831],[7,6178],[9,13264],[60,10373],[3,7955],[4,675],[25,4511],[3,3548],[24,4043],[13,27203],[7,6507],[8,13047],[1,228],[3,7518],[8,14671],[10,4875],[4,5928],[4,9405],[22,4091],[4,12723],[1,101],[10,5186],[37,6559],[21,3795],[45,8128],[24,4323],[7,3720],[4,4426],[24,16296],[4,7743],[24,4085],[8,3907],[10,3871],[2,1964],[2,210],[5,13508],[11,11075],[21,9787],[6,8170],[3,8008],[56,27350],[29,5003],[5,4146],[166,72159],[4,8772],[178,23063],[12,3201],[4,7716],[5,12672],[30,5498],[6,4614],[10,15835],[37,5768],[1301,283449],[5,6274],[3,9],[34,22911],[181,47823],[32,5501],[6,6538],[54,27201],[1,84],[3,7331],[27,4970],[37,16741],[4,8875],[23,3794],[22,3854],[10,11197],[22,1909],[4,7951],[519,72818],[6,3884],[23,3872],[20,7504],[11,9618],[2,2002],[5,12091],[3,7409],[12,5896],[6,4904],[6,2227],[16,6996],[5,3879],[100,17932],[24,4067],[22,3810],[3,4251],[22,3878],[7,3866],[55,9601],[3,8147],[28,4643],[16,7935],[15,11187],[20,3630],[5,11278],[11,6196],[4,9187],[60,28597],[6,10995],[41,6900],[26,4796],[2,7966],[13,3717],[31,3943],[12,8415],[26,4632],[7,474],[14,6383],[20,3639],[10,2390],[3,2138],[3,16302],[4,8704],[2,2560],[8,4051],[5,3972],[20,3658],[39,6846],[32,6800],[9,3794],[23,3982],[25,4220],[6,16312],[2,2093],[8,12609],[3,2771],[3,8007],[2,1970],[32,5779],[30,5416],[12,5906],[8,8823],[181,47823],[1,30],[8,4089],[4,5501],[2,2271],[22,3897],[18,19627],[5,12017],[30,5366],[8,3750],[27,3609],[3,7258],[8,76],[4,3758],[3,7380],[15,3741],[4,4036],[4,4490],[27,4892],[4,8401],[4,9025],[10,4271],[5,8132],[3,4182],[22,3656],[6,5424],[4,4046],[8,4880],[9,7900],[18,12993],[6,3600],[4,5778],[4,4607],[12,5806],[30,5334],[4,7750],[16,7527],[8,5555],[4,3653],[2,2617],[32,5681],[28,4706],[10,3949],[6,6376],[41,7582],[5,4605],[58,20112],[21,11297],[3,7416],[8,3901],[7,20184],[28,13840],[6,11582],[7,8122],[5,13981],[4,9796],[12,5234],[460,70291],[19,8932],[4,5606],[4,4985],[4,7149],[4,3832],[6,2729],[9,5851],[21,3605],[23,4161],[12,5753],[4,6814],[21,3784],[3,7132],[21,16313],[2,2622],[24,3987],[26,4663],[9,5668],[33,5745],[4,6790],[4,5216],[3,10801],[4,6701],[3,7838],[3,763],[8,7317],[8,3668],[8,4146],[1,382],[4,8447],[9,3890],[7,4371],[3,7359],[6,373],[13,3320],[4,8364],[8,3714],[4,4572],[324,75953],[30,5402],[16,7411],[11,4294],[20,3709],[4,8196],[4,4408],[39,6808],[3,3887],[4,4384],[4,3265],[10,4046],[6,17874],[3,5919],[7,109],[13,18655],[4,10177],[20,10348],[4,7471],[4,12935],[24,4306],[4,6170],[3,7246],[15,259],[25,6973],[24,4262],[9,15488],[8,4777],[4,5110],[8,4221],[3,1841],[4,8973],[8,6745],[13,16146],[49,8671],[4,8146],[11,4731],[6,11933],[3,7790],[8,4834],[6,16985],[7,8350],[24,4388],[72,31107],[15,6557],[29,5171],[13,15600],[1,258],[36,6372],[26,4285],[24,4366],[21,3673],[1,93],[6,8976],[4,5697],[277,39852],[4,9112],[4,7207],[5,7843],[12,6006],[7,5737],[5,11282],[4,3851],[18,3865],[9,4203],[10,3102],[3,7696],[3,14397],[11,22934],[23,4051],[5,6331],[22,3795],[59,10229],[14,6760],[9,7507],[16,1642],[4,4090],[12,4409],[10,4978],[9,13606],[35,6146],[3,17178],[9,742],[21,3697],[70,10064],[5,4437],[14,9378],[32,5568],[4,3710],[4,342],[3,7295],[7,4483],[24,4190],[4,4558],[3,7270],[4,4024],[6,3646],[37,6449],[1301,283449],[3,2095],[4,16752],[8,4149],[4,10562],[19,6475],[9,4923],[48,6132],[3,5995],[8,3741],[5,9330],[4,17],[23,3842],[6,3735],[12,5777],[10,4454],[23,4177],[16,14246],[4,16819],[4,6354],[4,4051],[18,8879],[21,3717],[8,4029],[10,5929],[36,6437],[58,10146],[3,7269],[10,4305],[7,109],[6,2766],[25,3736],[4,4056],[4,7989],[4,8086],[18,9533],[455,67667],[8,4196],[8,3631],[10,3732],[3,7576],[23,4051],[6,7754],[8,4485],[4,8340],[90,16668],[9,5206],[4,8456],[2,138],[11,17458],[3,7232],[22,3800],[12,4208],[15,5816],[22,3925],[3,5421],[19,8375],[4,6026],[3,5575],[8,4403],[4,4454],[4,13508],[7,2720],[20,3655],[3,7240],[16,9721],[29,4870],[181,47823],[46,9752],[14,5894],[11,12183],[29,5246],[14,5860],[3,7493],[20,5454],[2,2425],[12,1137],[41,6945],[3,5280],[3,3835],[2,31],[27,4973],[14,5946],[4,3916],[8,3606],[4,2135],[8,3875],[4,5639],[22,5667],[8,4325],[36,6072],[22,3809],[10,18556],[7,8277],[21,3862],[3,3600],[3,15690],[5,5201],[15,9716],[189,29074],[5,6523],[3,4022],[2,2775],[13,6308],[8,4029],[3,3768],[3,3824],[8,18774],[25,4529],[22,3708],[4,4396],[7,6504],[17,8496],[4,3698],[3,142],[8,88],[4,2954],[4,7703],[75,32177],[5,11887],[6,9023],[6,4299],[14,3658],[79,54140],[24,4315],[9,12801],[9,22230],[5,7378],[6,10319],[7,3648],[2,15287],[8,3795],[26,4272],[20,3827],[22,4042],[35,6161],[3,7689],[3,8352],[2,4369],[58,9744],[16,9054],[16,8643],[5,2694],[4,8216],[29,5311],[33,5867],[2,1823],[28,13343],[6,15392],[25,4325],[2,2893],[7,3743],[7,4163],[3,587],[519,72818],[8,3902],[7,9789],[7,5124],[19,10354],[38,6941],[3,5447],[189,29074],[19,3719],[4,7940],[4,8881],[10,3931],[10,1610],[10,4514],[8,5514],[2,149],[15,7600],[8,6930],[8,3855],[4,8048],[2,250],[1,48],[3,222],[26,4621],[46,8254],[4,4316],[2,21],[6,7149],[4,8447],[3,9675],[59,10216],[3,9544],[68,12079],[17,825],[4,7545],[3,9454],[33,5824],[4,7731],[7,5717],[8,14157],[22,3830],[3,7413],[27,4162],[2,1469],[22,3938],[4,9136],[4,11974],[1301,283449],[5,5796],[27,4738],[9,16524],[16,2822],[10,5134],[43,6931],[25,4252],[178,94509],[4,13366],[2,2400],[8,11497],[15,22562],[24,4028],[3,7620],[14,12186],[8,4186],[4,8306],[4,3643],[22,3981],[22,3932],[4,3295],[4,10618],[7,196],[307,46379],[7,4089],[2,23],[21,11845],[27,4892],[2,2149],[3,4756],[2,2945],[37,15092],[29,5017],[23,3908],[10,5363],[5,3765],[10,5792],[204,19555],[2,2839],[3,5405],[2,7082],[4,5434],[20,3611],[5,4116],[5,6135],[10,4992],[10,6146],[2,985],[22,9239],[679,96515],[24,4265],[4,11570],[19,15755],[17,6470],[12,6641],[6,9365],[8,3831],[8,4469],[21,3681],[11,4009],[4,4003],[3,7342],[2,3680],[9,17472],[15,3228],[4,8034],[43,7491],[2,812],[27,6443],[4,6345],[5,4640],[28,5020],[10,5000],[4,9024],[18,13725],[11,3465],[6,6004],[14,4529],[3,7501],[4,80],[22,3889],[8,4463],[4,4303],[11,6594],[4,10140],[22,3947],[34,5992],[4,4687],[33,5807],[6,6724],[5,2612],[6,11788],[19,9168],[17,7808],[16,4075],[8,13360],[25,4245],[15,9404],[4,8187],[3,7215],[24,4185],[1301,283449],[18,13610],[290,26209],[8,4061],[75,31057],[33,5767],[8,4160],[55,9910],[6,5844],[12,5088],[30,3092],[10,5101],[30,4944],[3,2260],[2,1932],[470,70423],[3,4328],[5,5706],[3,7657],[4,4263],[12,6277],[9,5399],[4,4536],[4,8704],[5,5213],[21,3791],[8,4616],[22,3971],[7,6998],[9,5473],[1,161],[3,4226],[29,5182],[13,4821],[3,7276],[3,5896],[8,4259],[13,5489],[6,3999],[9,5052],[3,7350],[3,7336],[10,5530],[8,4193],[7,8270],[24,3935],[4,10628],[5,7964],[3,152],[30,3108],[4,4146],[31,5400],[26,4704],[3,4563],[15,9271],[8,3371],[50,5373],[22,11427],[9,4507],[46,7784],[6,14580],[8,4123],[25,4294],[21,9770],[20,28014],[8,4405],[8,16201],[6,14795],[3,8118],[439,67001],[4,10751],[4,8395],[3,240],[3,7266],[6,3628],[4,7446],[10,14537],[14,12990],[46,7911],[189,29074],[35,5985],[34,6083],[4,3753],[23,2681],[3,4928],[2,2750],[7,3648],[5,7715],[3,5848],[25,9488],[4,9338],[21,3732],[8,3913],[2,2141],[9,6731],[44,7935],[4,9233],[7,3629],[25,12397],[21,3759],[4,6725],[25,4674],[1,4],[4,3803],[10,5892],[17,18576],[12,6194],[8,4338],[34,6150],[3,8002],[7,109],[9,11093],[5,4329],[3,8290],[519,72818],[16,8447],[33,16994],[4,4151],[4,5010],[12,7016],[4,6792],[39,6738],[27,11116],[5,5584],[9,4979],[12,13769],[4,3291],[3,4848],[3,4441],[8,3798],[8,4016],[4,8253],[3,5062],[8,15302],[8,4194],[7,3971],[3,8122],[7,4929],[8,3813],[3,7515],[9,272],[15,17723],[4,9654],[28,5059],[27,5024],[8,3607],[4,3722],[3,8178],[4,8910],[23,4062],[20,3611],[24,4350],[9,5461],[5,5025],[8,4034],[4,6735],[2,252],[4,5910],[5,322],[37,35072],[11,5852],[3,142],[3,9084],[8,5831],[4,7919],[3,3776],[8,3877],[47,8471],[24,4593],[4,7954],[8,3937],[4,3899],[2,182],[4,7618],[2,1838],[4,9257],[10,5216],[165,87621],[4,3733],[6,4807],[30,5309],[3,7224],[6,5545],[3,8950],[8,4300],[4,7638],[22,3896],[25,4472],[6,10609],[16,6349],[1,193],[10,4872],[29,4880],[6,3193],[2,6],[3,5400],[20,21058],[9,4994],[7,3802],[4,4731],[3,9273],[2,2945],[4,10961],[22,6074],[1301,283449],[3,7459],[4,8161],[22,3919],[15,9249],[4,6558],[312,53350],[7,3657],[3,9471],[6,6828],[8,3912],[6,13333],[3,7322],[4,8683],[21,3765],[6,5878],[22,3612],[3,7905],[9,7068],[17,8869],[3,4248],[3,4215],[10,5840],[8,3935],[4,9037],[8,4428],[4,7458],[4,10346],[39,6899],[3,8025],[2,3138],[3,9345],[46,8736],[21,3870],[28,4673],[3,4900],[1,24],[3,7550],[10,21994],[1,11],[8,3931],[21,9714],[17,6523],[22,3789],[4,9014],[3,6572],[4,45],[8,4369],[14,6921],[3,7781],[23,3821],[5,5418],[24,4210],[4,4253],[4,9626],[3,2798],[27,4874],[10,5323],[11,8511],[34,6030],[3,6138],[4,8443],[8,3786],[12,9940],[6,6156],[5,13400],[37,6801],[7,17452],[3,3732],[5,14252],[9,9997],[12,5867],[20,15243],[41,9434],[18,8502],[30,5271],[189,29074],[30,3098],[24,3976],[34,5750],[20,3620],[2,2200],[9,3643],[5,194],[25,12892],[16,11253],[42,7353],[23,14984],[6,9298],[4,11003],[1213,127531],[202,98394],[28,5016],[10,4757],[6,13440],[30,5033],[2,12],[7,10231],[524,74940],[14,7027],[9,6541],[3,2904],[3,7320],[4,8905],[11,4577],[10,5721],[5,2170],[22,3860],[33,5959],[7,15693],[15,35477],[3,7407],[3,7304],[10,3916],[6,4110],[6,1137],[4,7977],[21,4902],[48,8503],[51,9032],[24,12184],[5,13266],[14,6369],[23,4177],[25,4268],[4,4329],[3,7183],[22,3954],[26,4564],[6,3765],[10,5022],[6,5040],[11,5603],[24,4218],[3,4362],[6,14181],[4,5954],[21,3672],[5,7626],[20,3607],[1606,365809],[4,7938],[39,7302],[20,3695],[6,7488],[3,7562],[55,8602],[3,9336],[4,1010],[4,7290],[16,1642],[2,7496],[3,10225],[7,4420],[38,8114],[97,48863],[26,4617],[4,4347],[4,8050],[6,4129],[25,3780],[25,4411],[6,12693],[43,7302],[43,7145],[3,3013],[4,9030],[26,4416],[5,5628],[21,3653],[24,4511],[35,5887],[256,21817],[3,64],[19,6475],[9,4507],[28,15041],[3,6506],[6,278],[2,2963],[28,5004],[17,6429],[6,9813],[6,10296],[4,11420],[6,4640],[1,9],[31,5670],[20,3615],[8,3893],[8,4401],[4,4532],[20,11430],[23,2681],[6,3610],[13,12622],[24,4382],[10,4792],[3,4953],[20,3610],[4,7892],[6,14227],[23,4062],[60,10326],[27,4757],[42,7467],[1,84],[2,119],[52,9233],[3,7247],[38,4749],[8,8355],[23,8912],[26,3807],[6,6313],[3,4127],[23,4061],[8,10053],[2,2094],[6,12242],[3,8141],[5,4274],[14,17452],[30,4452],[2,214],[4,3600],[6,6150],[27,4107],[13,199],[40,7063],[3,8082],[3,7412],[10,17838],[13,6034],[29,5271],[8,25704],[5,5314],[6,2291],[6,10833],[23,3979],[69,12305],[44,13745],[4,8851],[3,6967],[35,9592],[12,4154],[3,7639],[3,7349],[19,22321],[6,261],[19,4148],[23,4284],[32,5447],[1301,283449],[8,4478],[6,6204],[7,4002],[5,12323],[21,3735],[26,4413],[4,8544],[26,12323],[6,16620],[21,3797],[5,6677],[12,4740],[2,2013],[4,6027],[20,3612],[3,734],[5,9370],[8,7251],[10,4671],[9,785],[24,11656],[5,3615],[41,7097],[21,3845],[13,4724],[1301,283449],[31,5302],[26,2801],[4,4534],[10,13235],[21,8111],[31,5642],[182,91718],[8,18485],[4,5670],[13,6316],[10,4424],[5,40],[5,5888],[8,4071],[8,3633],[5,4563],[35,5619],[38,17556],[3,9009],[4,4697],[5,4271],[27,5025],[3,7445],[4,198],[5,5384],[7,260],[15,4991],[7,4114],[14,8425],[3,8324],[4,33],[32,5131],[1301,283449],[2,127],[8,3648],[20,7670],[24,3724],[11,3575],[20,3626],[4,4387],[9,3732],[3,3940],[5,5221],[33,6061],[16,2670],[8,4387],[5,5884],[13,15885],[43,7757],[6,12944],[44,7719],[4,8001],[7,7346],[39,6597],[15,21199],[4,4030],[29,5130],[7,3232],[4,2365],[36,6539],[21,3669],[4,3759],[3,3706],[3,4754],[4,4697],[8,20741],[1,5],[4,5008],[42,7397],[31,5374],[4,11756],[28,4782],[45,15100],[30,5423],[4,16657],[4,7745],[53,25355],[11,5581],[13,20672],[370,51751],[2,39],[11,5520],[43,9100],[21,3828],[14,4227],[4,9191],[1301,283449],[18,6633],[6,12782],[8,4398],[3,7368],[8,4267],[38,3251],[18,12707],[47,20667],[5,6199],[13,199],[32,5742],[37,6448],[28,4945],[39,7040],[10,5005],[11,41113],[225,119372],[29,5209],[4,8786],[5,3850],[8,4063],[29,13558],[26,4639],[20,3443],[4,8239],[19,6085],[8,4163],[1301,283449],[90,49419],[5,4309],[1,28],[14,6649],[3,8222],[5,2579],[4,8316],[34,5196],[3,9291],[5,3614],[28,4858],[42,6461],[11,7330],[3,7048],[23,4075],[32,5612],[5,11577],[98,72058],[21,3728],[23,3962],[7,4116],[26,6284],[3,7263],[47,8334],[30,5366],[14,16660],[6,6008],[23,4135],[6,7841],[12,5510],[80,34182],[3,9055],[6,2711],[6,16183],[9,5144],[1,3],[712,160017],[3,3872],[12,12738],[3,8113],[35,6058],[6,12786],[4,2904],[14,6853],[5,2585],[21,8050],[123,91940],[27,32446],[5,4032],[3,3916],[4,8213],[3,6252],[3,6011],[4,6597],[6,2717],[3,7424],[24,4480],[4,7307],[4,11548],[30,5491],[4,7428],[22,3636],[31,5497],[4,5351],[21,3823],[13,5830],[30,4866],[47,17735],[10,5136],[4,8586],[20,3443],[58,16892],[23,4053],[8,4550],[6,11739],[4,4337],[8,3739],[10,4655],[26,13042],[1,653],[9,5733],[2,216],[25,4534],[7,8053],[3,462],[4,8489],[4,3919],[17,4022],[23,7875],[23,32430],[9,16417],[29,12354],[2,5858],[4,7536],[22,3739],[8,3807],[8,6557],[28,4632],[4,8266],[3,972],[12,8817],[24,3884],[4,3103],[26,4372],[37,14440],[33,5876],[8,4240],[3,8626],[25,4053],[39,7017],[3,7607],[24,4434],[4,10539],[3,7513],[6,3792],[1,202],[5,4405],[2,2399],[9,7813],[26,4486],[10,4623],[38,6679],[3,7225],[7,4261],[3,9395],[4,10016],[56,9946],[47,8057],[312,53350],[6,3762],[3,3867],[11,5589],[2,6524],[8,4359],[10,12779],[22,3815],[21,10598],[4,9853],[3,7682],[24,4245],[4,8953],[179,3958],[5,679],[9,4153],[4,777],[9,12625],[8,3628],[31,5453],[8,10530],[6,10744],[65,13636],[7,109],[8,767],[7,9468],[4,4798],[23,3970],[9,6462],[7,4199],[2,3600],[26,4816],[5,7176],[4,3661],[29,5157],[4,3725],[4,12309],[12,5661],[12,5004],[9,5495],[24,26431],[3,7204],[14,14383],[6,18067],[24,4166],[5,5081],[5,516],[51,9232],[10,14104],[24,4195],[3,7687],[8,3823],[4,4610],[6,6587],[21,9375],[6,4384],[20,3611],[7,12075],[39,6648],[31,5528],[4,10112],[18,5829],[4,7090],[7,3989],[5,3614],[24,3799],[9,5413],[8,8990],[23,4258],[9,632],[6,5282],[8,4036],[3,7355],[26,4633],[3,4718],[4,8313],[1,1129],[6,3739],[35,6327],[828,116783],[24,12980],[1,60],[4,3612],[8,768],[33,5778],[8,4091],[25,4537],[30,5482],[7,109],[7,3870],[47,8374],[7,11136],[17,7387],[6,625],[24,4377],[4,5584],[4,8185],[23,4142],[11,8180],[21,9101],[32,5592],[66,33636],[4,3704],[4,7646],[258,120072],[26,4444],[41,16596],[218,103574],[9,9028],[3,7444],[21,3612],[1301,283449],[6,3799],[12,6278],[6,13734],[27,2791],[41,7384],[3,10864],[23,4075],[21,21286],[4,4587],[6,399],[5,4416],[9,1860],[29,5066],[21,3712],[9,3604],[3,10800],[35,6488],[3,9072],[10,4916],[48,8052],[4,9891],[24,12833],[3,7684],[9,4943],[4,14300],[5,12975],[50,8789],[3,3273],[3,9343],[22,3840],[11,18001],[5,3293],[2,2162],[6,16588],[4,5697],[3,8270],[10,4882],[3,4977],[22,3853],[1,12],[49,8678],[2,2181],[10,4081],[17,6055],[84,20945],[18,6780],[22,4003],[4,6583],[12,5798],[181,47823],[3,10019],[2,2999],[12,4868],[8,3732],[3,8738],[3,4666],[12,6203],[3,4399],[27,4875],[37,6581],[7,13348],[25,4594],[20,3636],[17,8492],[17,12234],[6,3877],[6,5054],[4,7471],[28,3626],[5,11736],[1301,283449],[2,2931],[21,3769],[4,5320],[4,3427],[8,5002],[8,3977],[22,3989],[4,8411],[4,8126],[5,7649],[6,7214],[6,11633],[23,4055],[6,3677],[6,4557],[4,8878],[3,3941],[5,14646],[7,1998],[2,3478],[3,4330],[29,4843],[9,8039],[8,88],[15,9914],[189,29074],[8,9843],[3,4756],[7,487],[7,4901],[44,15256],[8,3666],[37,6673],[6,3628],[7,2253],[4,9111],[23,4200],[6,13976],[65,9424],[23,8420],[3,10801],[4,10515],[2,2851],[11,12772],[11,25697],[4,4695],[21,11768],[2,2787],[20,3617],[3,7401],[3,3851],[4,6721],[8,3857],[29,4877],[34,5980],[9,10514],[24,4148],[12,3988],[67,11947],[3,7598],[23,4153],[10,5353],[29,5261],[2,3005],[16,13900],[10,5244],[26,31227],[10,5221],[4,4016],[6,2994],[30,11079],[6,606],[8,3734],[4,7629],[8,3842],[4,9839],[27,4804],[20,3610],[3,6820],[9,5745],[6,5418],[3,8020],[16,5362],[4,7788],[181,47823],[3,10123],[12,5444],[39,7074],[9,6802],[23,11420],[8,3987],[5,12554],[16,24416],[15,8545],[3,8155],[3,3816],[26,4505],[3,4520],[11,6072],[1,40],[8,4529],[5,3010],[3,10659],[24,3957],[8,4493],[8,3843],[4,8329],[25,4189],[4,7050],[4,870],[4,6767],[33,5937],[24,4260],[4,5291],[4,7782],[6,341],[10,5711],[25,3813],[18,10153],[24,4033],[3,4098],[21,16313],[7,3924],[11,7159],[6,4492],[2,2690],[6,16201],[7,109],[9,4892],[27,4751],[4,9891],[13,4089],[4,4131],[11,12079],[5,6833],[7,864],[21,3763],[2,2506],[8,4009],[2,2773],[21,3701],[4,10823],[25,3996],[22,3991],[25,4068],[2,2387],[15,8483],[8,11433],[8,4160],[40,7053],[23,3973],[5,12866],[7,8392],[3,17292],[28,5074],[8,4534],[8,4121],[25,9866],[4,3909],[1301,283449],[6,9452],[13,6703],[4,8047],[2,3605],[3,8605],[8,6017],[2,3085],[5,3859]])

In [5]:
X

array([[   4, 3658],
       [   3, 7231],
       [  23, 3723],
       ..., 
       [   8, 6017],
       [   2, 3085],
       [   5, 3859]])

In [6]:
Y = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,2,1,1,1,2,1,1,2,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,2,1,1,1,1,1,2,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,2,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,2,1,1,1,1,1,2,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,2,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1])

In [7]:
Y

array([1, 1, 1, ..., 1, 1, 1])

In [8]:
clf = GaussianNB()

NameError: name 'GaussianNB' is not defined

In [9]:
clf = GaussianNB()

NameError: name 'GaussianNB' is not defined

In [10]:
from sklearn import GaussianNB

ImportError: cannot import name 'GaussianNB'

In [11]:
from sklearn.naive_bayes import GaussianNB

In [12]:
clf = GaussianNB()

In [13]:
clf.fit(X,Y)

GaussianNB()

In [14]:
print(clf.score(X,Y))

0.976653696498


In [15]:
clf.predict(10,40)

TypeError: predict() takes 2 positional arguments but 3 were given

In [16]:
clf.predict([10,50])

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [17]:
clf.predict([200,500230])

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [18]:
clf.predict([200,500230])

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [19]:
clf.predict([200,500230])

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [20]:
clf.predict([20,1245])

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])